## Numpy

1. ilk numpy array iniz:

In [9]:
players = [180, 215, 210, 210, 188, 176, 209, 200]

# numpy kutuphanesini np olarak import ediniz
import numpy as np

# 'players' listesini kullanarak bir numpy array'i olusturun: np_players

np_players = np.array(players)

# np_players'in tipini yazdiriniz
type(np_players)
np_players

array([180, 215, 210, 210, 188, 176, 209, 200])

2. numpy arrayi ile islemler:

In [10]:
# normal liste tipinde:
boy_inc = [74,74,72,72,73,69,74,70,73,75]

# numpy'i import ediniz
import numpy as np

# boy_inc i kullanarak bir numpy arrayi olusturunuz: np_boy_inc adiyla kaydediniz
np_boy_inc = np.array(boy_inc)

# np_boy_inc i yazdiriniz
print(np_boy_inc)

# np_boy_inc i metre cinsine ceviriniz: np_boy_m aduyla kaydediniz
np_boy_m = np_boy_inc * 0.0254

# np_boy_m 'i yazdiriniz
print(np_boy_m)

[74 74 72 72 73 69 74 70 73 75]
[1.8796 1.8796 1.8288 1.8288 1.8542 1.7526 1.8796 1.778  1.8542 1.905 ]


NOT: bu jupiter notebook uzerindeki tum degiskenleri diger hucrelerde kullanabiliriz. ayni isimli iki farkli degisken icin son calistirdigimiz degisken kullanilir.

3. Burada sporcularin vucut BMI degerlerini bulacagiz. BMI degeri, kilonun(kg) boyun(m) karesine bolunmesi ile elde ediliyor.

In [12]:
# NOT: Bir kutuphaneyi bir defa import edip calistirmamiz yeterlidir. Ama burda ogrenme amacli tekrar soruyoruz.
# numpy'i import ediniz


# boy_inc 'i tekrar yazmak mecburiyetinde olmasak da gozununde olmasi icin listeyi tekrar yaziyoruz. 
# ilerde bu tekrarlar azalacaktir:
boy_inc = [74,74,72,72,73,69,74,70,73,75]

agirlik_po = [180,215,210,210,188,176,209,200,231,180]

# boy_inc'i numpy arrayine cevirip metre cinsi ile kaydedelim: np_boy_m
np_boy_m = np.array(boy_inc) * 0.0254

# agirlik_po'i numpy arrayine cevirip kg cinsi ile kaydediniz: np_agirlik_kg
np_agirlik_kg = np.array(agirlik_po    ) * 0.453592

# BMI'i hesaplayiniz: bmi 
bmi = np_agirlik_kg / (np_boy_m)**2

# bmi degiskenini yazdiriniz (bmi haddi zatinda bir degiskendir, turu listedir)
print(bmi)


[23.11037639 27.60406069 28.48080465 28.48080465 24.80333518 25.99036864
 26.83371481 28.69669413 30.47643843 22.4982082 ]


In [14]:
# NOT: Normal listeler de ve numpy array'lerinde de ayni sekilde 
# [] koseli parantez icinde indis numarasi kullanarak elemanlara ulasiyoruz
x = [42 , 19 , 16, 13, 51]
x[1]
import numpy as np
y = np.array(x)
y[4]

51

4. Zayif sporculari bulalim:

In [15]:
# ornek kod:

# 22 den buyuk olanlari 'buyuk' adli bir listede tutuyoruz, bunu y listesinde indis olarak kullaniyoruz
buyuk = y > 22
y[buyuk]

array([42, 51])

In [16]:
print(buyuk)         # goruldugu uzere 'buyuk' listesi True-False lardan olusan bir liste

[ True False False False  True]


In [17]:
print(y)     # y listesinde indis olarak kullandigimizda True'nun denk geldigi elemani secer

[42 19 16 13 51]


In [18]:
y[buyuk]   # boylece 22 den buyuk sayilari secmis oluruz

array([42, 51])

In [19]:
y[ y>22 ]   # Ayni secimi araci bir degisken ismi olusturmadan dogrudan indis yerine yazarak da yapabiliriz

array([42, 51])

5. bmi degeri 21 den kucuk olan bmi degerlerini secelim:

In [21]:
# bmi listesi uzerinde islem yapip 23 den kucuk olup olmadiklarini belirten 'zayif' adli bir array olusturunuz (True-False arrayi): 
zayif = bmi < 23

# zayif arrayini yazdiriniz
print(zayif)

# zayif arrayini indis olarak kullanip 23ten kucuk olan bmi degerlerini yazdiriniz
print(bmi[zayif])

[False False False False False False False False False  True]
[22.4982082]


6. Numpy elemanlari tek tip olarak tutur. Oysa normal python listeleri farkli tipte elemanlari oldugu gibi tutuyor. 
Peki, karisik bir listeyi np.array() ile numpy arrayi yaparsak numpy arrayi nasil davranir, bakalim.

In [ ]:
np.array([True, 1, 2]) + np.array([3, 4, False])

In [22]:
[True, 1, 2] + [3, 4, False]

[True, 1, 2, 3, 4, False]

7. Goruldugu gibi numpy arrayi ve normal python listesi + - * / gibi islemlerde farkli davraniyor.

In [23]:
np.array([4, 3, 0]) + np.array([0, 2, 2])      # True = 1 ve False = 0 olarak aldi.

array([4, 5, 2])

In [24]:
boy_inc = [74,74,72,72,73,69,74,70,73,75]
agirlik_po = [180,215,210,210,188,176,209,200,231,180]

# verilen listeleri npy arrayi olarak kaydediniz: np_boy_inc ve np_agirlik_po olarak.
np_boy_inc = np.array(boy_inc)
np_agirlik_po = np.array(agirlik_po)

# np_agirlik_po arrayinin 5. elemanini yazdiriniz
np_agirlik_po[4]

# np_boy_inc arrayinin 5. ile 8. elemanlari arasini yazdiriniz. (5 ve 8 dahil)
np_agirlik_po[4:9]

array([188, 176, 209, 200, 231])

8. Iki boyutlu numpy arrayi

In [28]:
sporcular = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# numpy i import ediniz


# sporcular listesini kullanarak 2 boyutlu numpy arrayini olusturunuz: np_sporcular
np_sporcular = np.array(sporcular)

# np_sporcular in tipini yazdiriniz
print(type(np_sporcular))

# np_sporcular in boyutunu yazdiriniz
np_sporcular.shape

<class 'numpy.ndarray'>


(4, 2)

9. BILGI: cok boyutlu normal liste ve array arasindaki fark:

In [29]:
# normal liste ici liste
x = [["a", "b"], ["c", "d"]]
[x[0][0], x[1][0]]

['a', 'c']

In [2]:
# numpy arrayi
import numpy as np
np_x = np.array(x)
np_x[:,0]           # kesisiminde kalan elemani secme mantigi

NameError: name 'x' is not defined

10. cok boyutlu arraylerde indisle secme islemleri:

In [33]:
sporcular = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# arrayi numpy arrayine ceviriniz: np_sporcular
np_sporcular = np.array(sporcular)

# arrayin 3. elemanini yazdiriniz
np_sporcular[2]

array([210. ,  98.5])

In [34]:
# np_sporcular arrayinin ilk sutununun hepsini yazdiriniz
np_sporcular[:,0]                         # (kesisim mantigi)

array([180., 215., 210., 188.])

In [35]:
# np_sporcular arrayinin ikinci sutununun hepsini yazdiriniz
np_sporcular[:,1]

array([ 78.4, 102.7,  98.5,  75.2])

In [37]:
# np_sporcular arrayinin 3. satirinin  1.sutundaki degeri yazdiriniz
np_sporcular[2,0]

210.0

In [39]:
sporcular3 = [[74.0, 180.0, 22.99],
 [74.0, 215.0, 34.69],
 [72.0, 210.0, 30.78],
 [72.0, 210.0, 35.43],
 [73.0, 188.0, 35.71],
 [69.0, 176.0, 29.39]]

# numpy arrayine ceviriniz: np_sporcular3
np_sporcular3 = np.array(sporcular3)

# birimleri degistirmek icin ilgili katsayilar
katsayilar = np.array([0.0254, 0.453592, 1])

# katsayilar ile carparak, np_sporcular3 un kg m cinsinden yazdiriniz
np_sporcular3 * katsayilar

array([[ 1.8796  , 81.64656 , 22.99    ],
       [ 1.8796  , 97.52228 , 34.69    ],
       [ 1.8288  , 95.25432 , 30.78    ],
       [ 1.8288  , 95.25432 , 35.43    ],
       [ 1.8542  , 85.275296, 35.71    ],
       [ 1.7526  , 79.832192, 29.39    ]])

11. Numpy ile basit istatistikler: np.mean() np.median()

In [6]:
sporcular4 = [[7.400e+04, 1.800e+02, 2.299e+01],
              [7.400e+01, 2.150e+02, 3.469e+01],
              [7.200e+01, 2.100e+02, 3.078e+01],
              [7.200e+01, 2.100e+02, 3.543e+01],
              [7.300e+01, 1.880e+02, 3.571e+01],
              [6.900e+01, 1.760e+02, 2.939e+01],
              [6.900e+01, 2.090e+02, 3.077e+01],
              [7.100e+01, 2.000e+02, 3.507e+01]]

np_sporcular4 = np.array(sporcular4)

# ilk sutunu seciniz: np_boy_inc olarak kaydidiniz
np_boy_inc = np_sporcular4[:,0]

# boy ortalamasini yazdiriniz
np.mean(np_boy_inc)

# boy degerlerinin ortanca olanini yazdiriniz
np.median(np_boy_inc)

72.0

In [10]:
# boy ortalamasi (1. kolon/sutun)
ort = np_boy_inc
print("Boy ortalamasi: " , np.mean(ort))

# boy medyan degeri:
med = np.median(np_boy_inc)
print("Medyan: " ,    med     )

# boylarin standart sapmasi:
s_sapma = np.std(np_boy_inc)
print("Standart sapmasi: " + str(s_sapma))

Boy ortalamasi:  9312.5
Medyan:  72.0
Standart sapmasi: 24449.57690329221


12. Bu baslik sonunda bos hucre ekleyerek Numpy ile ilgili karalama, test etme, uygulama, deneme-yanilma, farkli kombinasyonlari denemeler yapiniz:

# Pandas

13. sozlukten Dataframe olusturma:  pd.DataFrame()

In [12]:
isimler = ['United States', 'Australia', 'Japan', 'India', 'Russia', 'Morocco', 'Egypt']
direks_sag =  [True, False, False, False, True, True, True]
arac = [809, 731, 588, 18, 200, 70, 45]

# pandas kutuphanesini import ediniz
import pandas as pd

# verilen listeleri kullanarak sozlugum adli bir sozluk olusturunuz. 
# degisken adlari:  ulkeler,  direksiyon_sag,  arac_sayisi
sozlugum = { 'ulkeler': isimler   , 'direksiyon_sag':direks_sag   , 'arac_sayisi': arac   }

# 'sozlugum' adli sozluk u Dataframe e ceviriniz: 'araclar' ismi ile kaydediniz
araclar = pd.DataFrame(sozlugum)

# bu dataframe i yazdiriniz
araclar

ulkeler  direksiyon_sag  arac_sayisi
0  United States            True          809
1      Australia           False          731
2          Japan           False          588
3          India           False           18
4         Russia            True          200
5        Morocco            True           70
6          Egypt            True           45

14. gozlem indeksleri atama: df.index =

In [13]:
satir_indeksleri = ['US', 'AUS', 'JAP', 'IN', 'RU', 'MOR', 'EG']

# verilen diziyi araclar dataframe inin indeksi icin kullaniniz
araclar.index = satir_indeksleri

# araclar dataframe ini tekrar yazdiriniz
araclar

ulkeler  direksiyon_sag  arac_sayisi
US   United States            True          809
AUS      Australia           False          731
JAP          Japan           False          588
IN           India           False           18
RU          Russia            True          200
MOR        Morocco            True           70
EG           Egypt            True           45

15. csv dosyasi okuma:

In [14]:
# pandas i import ediniz:

import pandas as pd
# cars.csv  dosyasini cars adi ile kaydediniz
cars = pd.read_csv('cars.csv')

# cars verisinin ilk 5 gozlemini yazdiriniz
cars.head()

Unnamed: 0  cars_per_cap        country  drives_right
0         US           809  United States          True
1        AUS           731      Australia         False
2        JAP           588          Japan         False
3         IN            18          India         False
4         RU           200         Russia          True

16. ilk kolonu satirlarin indeksi olarak acmak icin kulanilan arguman:  index_col = 0

In [17]:
# ilk sutun gozlemlerin indeksi olarak belirlenmis olarak csv dosyasini okuyunuz:
cars = pd.read_csv('cars.csv',  index_col=[0]     )


# cars verisini tekrar yazdiriniz'
cars

cars_per_cap        country  drives_right
US            809  United States          True
AUS           731      Australia         False
JAP           588          Japan         False
IN             18          India         False
RU            200         Russia          True
MOR            70        Morocco          True
EG             45          Egypt          True

17. Koseli parantezle degisken secme :

In [19]:
# country degiskenini bir Pandas Series olarak yazdiriniz
print(cars['country'])

# country degiskenini bir  Pandas DataFrame olarak yazdiriniz
print(cars[['country']])

# dataframe in sadece country ve drives_right degiskenlerini secerek yazdiriniz
print(cars[['country', 'drives_right']])

US     United States
AUS        Australia
JAP            Japan
IN             India
RU            Russia
MOR          Morocco
EG             Egypt
Name: country, dtype: object
           country
US   United States
AUS      Australia
JAP          Japan
IN           India
RU          Russia
MOR        Morocco
EG           Egypt
           country  drives_right
US   United States          True
AUS      Australia         False
JAP          Japan         False
IN           India         False
RU          Russia          True
MOR        Morocco          True
EG           Egypt          True


18. Koseli parantezle gozlem secme :

In [21]:
# cars verisinin ilk 3 gozlemi yazdiriniz
print(cars[0:3])

# 4. 5. ve 6. gozlemleri yazdiriniz
cars[3:6]

     cars_per_cap        country  drives_right
US            809  United States          True
AUS           731      Australia         False
JAP           588          Japan         False


cars_per_cap  country  drives_right
IN             18    India         False
RU            200   Russia          True
MOR            70  Morocco          True

19. loc ve iloc:

In [22]:
# sadece Japonya ya ait bilgileri yazdiriniz
print(cars.loc['JAP'])

# Avusturya ve Misira ait bilgileri yazdiriiniz
print(cars.loc[['JAP', 'AUS']])

cars_per_cap      588
country         Japan
drives_right    False
Name: JAP, dtype: object
     cars_per_cap    country  drives_right
JAP           588      Japan         False
AUS           731  Australia         False


20. loc ve iloc 2:

In [30]:
# Morocco a ait drives_right bilgisini yazdiriniz
print(cars.loc['MOR']['drives_right'])

# rusya ve morocco nun country ve drives_right bilgilerini yazdiriniz:
print(cars.loc[['RU','MOR'],['country','drives_right']])


True
     country  drives_right
RU    Russia          True
MOR  Morocco          True


21. loc ve iloc 3:

In [34]:
# drives_right kolonunu(degiskenini) bir Series olarak yazdiriniz:
print(cars.loc[:,'drives_right'])

# drives_right kolonunu(degiskenini) bir DataFrame olarak yazdiriniz:
print(cars.loc[:,['drives_right']])

# cars_per_cap ve drives_right kolonlarini(degiskenlerini) bir DataFrame olarak yazdiriniz:
print(cars.loc[:,['cars_per_cap','drives_right']])


US      True
AUS    False
JAP    False
IN     False
RU      True
MOR     True
EG      True
Name: drives_right, dtype: bool
     drives_right
US           True
AUS         False
JAP         False
IN          False
RU           True
MOR          True
EG           True
     cars_per_cap  drives_right
US            809          True
AUS           731         False
JAP           588         False
IN             18         False
RU            200          True
MOR            70          True
EG             45          True


22. Pandas DataFrame uzerinde filtreleme:     df[df['column1']]

In [39]:
# sag direksiyonlu olanlari ifade eden drives_right kolonunu bir Series olarak dr adiyla kaydediniz: dr
dr = cars['drives_right']

#  dr i kullanarak cars dataframini filtreleyiniz, secilen adi ile kaydediniz: secilen
# (burada dr icindeki True lara karsilik gelen gozlemleri secilir, digerleri secilmez)
secilen = cars[dr]

# secilen  dataframini yazdiriniz
secilen


cars_per_cap        country  drives_right
US            809  United States          True
RU            200         Russia          True
MOR            70        Morocco          True
EG             45          Egypt          True

In [38]:
cars[~cars['drives_right']] #false lari dondurur

cars_per_cap    country  drives_right
AUS           731  Australia         False
JAP           588      Japan         False
IN             18      India         False

23. tek satirda ayni islem:

In [40]:
# Yukaridaki secme islemini aynisini tek satirda yapiniz:

secilen1 = cars[cars['drives_right']]
# secilen  dataframe ini yazdiriniz:
secilen1

cars_per_cap        country  drives_right
US            809  United States          True
RU            200         Russia          True
MOR            70        Morocco          True
EG             45          Egypt          True

24. Filtreleme-Secme 2:

In [42]:
# cars_per_cap degeri 500 den buyuk olan degerleri seciniz. bu veriyi  car_maniac  adiyla kaydediniz 
cpc = cars['cars_per_cap']
many_cars = cpc > 500
car_maniac = cars[many_cars]

#  car_maniac  verisini yazdiriniz
car_maniac

cars_per_cap        country  drives_right
US            809  United States          True
AUS           731      Australia         False
JAP           588          Japan         False

25. Filtreleme-Secme 3:

In [50]:
import numpy as np

# cars_per_cap degeri 500 den buyuk ve 100 den kucuk olan degerleri seciniz. bu veriyi  medium  adiyla kaydediniz

medium = cars[np.logical_and(cpc > 100 , cpc < 500)]
# medium u yazdiriniz
medium

cars_per_cap country  drives_right
RU           200  Russia          True

26. DataFrame uzerinde dongu

In [49]:
# cars uzerinde for ile dongu kurarak degisken adini ve satiri yazdiriniz
for variable, row in cars.iterrows():
    print(row)
    

cars_per_cap              809
country         United States
drives_right             True
Name: US, dtype: object
cars_per_cap          731
country         Australia
drives_right        False
Name: AUS, dtype: object
cars_per_cap      588
country         Japan
drives_right    False
Name: JAP, dtype: object
cars_per_cap       18
country         India
drives_right    False
Name: IN, dtype: object
cars_per_cap       200
country         Russia
drives_right      True
Name: RU, dtype: object
cars_per_cap         70
country         Morocco
drives_right       True
Name: MOR, dtype: object
cars_per_cap       45
country         Egypt
drives_right     True
Name: EG, dtype: object


27. DataFrame uzerinde dongu-2

In [53]:
# bir ustteki hucrede yazilanlari cikti olarak elde ediniz. (df uzerinde dongu kullanarak)
for var, row in cars.iterrows() :
    print(   var,':',     row['cars_per_cap']  )

US : 809
AUS : 731
JAP : 588
IN : 18
RU : 200
MOR : 70
EG : 45


28. Dongu ile bir degiskeni editleyip baska bir degisken olarak df e ekleme

In [ ]:
cars

In [55]:
# Cars verisi uzerinde goruldugu gibu country adli bir degisken var. df uzerinde for dongu ile bu degiskeni kullanip 
# ayni ulke isimlerinin buyuk harfli halini barindiran yeni bir degisken olarak bu veriye ekleyiniz.
# yeni degiskenin adi de COUNTRY seklinde olsun
for var,row in cars.iterrows():
    cars.loc[var,'COUNTRY'] = row['country'].upper()
    
# df i yazdiriniz
cars

cars_per_cap        country  drives_right        COUNTRY
US            809  United States          True  UNITED STATES
AUS           731      Australia         False      AUSTRALIA
JAP           588          Japan         False          JAPAN
IN             18          India         False          INDIA
RU            200         Russia          True         RUSSIA
MOR            70        Morocco          True        MOROCCO
EG             45          Egypt          True          EGYPT

29. dongu yerine .apply() methodu:

In [56]:
import pandas as pd
# cars verisinin ilk halini tekrar cagiralim:
cars = pd.read_csv('cars.csv', index_col = 0)

# 28. soruda yapilan ayni seyi .apply(str.upper)  yontemi ile yapiniz. (Bilgiye dikkat!)
cars['COUNTRY']= cars['country'].apply(str.upper)

# cars df sini yazdiriniz
cars

cars_per_cap        country  drives_right        COUNTRY
US            809  United States          True  UNITED STATES
AUS           731      Australia         False      AUSTRALIA
JAP           588          Japan         False          JAPAN
IN             18          India         False          INDIA
RU            200         Russia          True         RUSSIA
MOR            70        Morocco          True        MOROCCO
EG             45          Egypt          True          EGYPT

30. Bu baslik sonunda bos hucre ekleyerek Pandas ile ilgili karalama, test etme, uygulama, deneme-yanilma, farkli kombinasyonlari denemeler yapiniz: